package com.panacea.shopshop.model;

import lombok.Data;

@Data
public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbg.generated  Thu Jun 01 15:40:14 JST 2023
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.name
	 * @mbg.generated  Thu Jun 01 15:40:14 JST 2023
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.price
	 * @mbg.generated  Thu Jun 01 15:40:14 JST 2023
	 */
	private Double price;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbg.generated  Thu Jun 01 15:40:14 JST 2023
	 */
	
}